{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer | quote }}
    nginx.ingress.kubernetes.io/ssl-redirection: "true"
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host.host }}
      http:
        paths:
          - path: {{ $path.path | default "/" }}
            pathType: {{ $path.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $.Values.service.name }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
  tls:
    {{- range $host := .Values.ingress.hosts }}
    - hosts:
      - {{ $host.host }}
      secretName: {{ $host.secretName | default (printf "%s-ingress-tls" $host.host) }}
    {{- end }}
  ingressClassName: {{ .Values.ingress.class | default "nginx" }}
{{- end }}