{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.ingress.class | default "nginx" }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path | default "/" | quote }}
            pathType: {{ .pathType | default "Prefix" | quote }}
            backend:
              service:
                name: {{ $.Values.service.name | default "default-service" | quote }}
                port:
                  number: {{ (index $.Values.service.ports 0).port | default 80 }}
    {{- end }}
  tls:
    {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ .host | quote }}
      secretName: {{ .secretName | default (printf "%s-ingress-tls" .host) | quote }}
    {{- end }}
{{- end }}
