name: Deploy Helm Chart to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different
    paths:
      - 'charts/**'  # Trigger only when chart files change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.17.0  # Adjust to the latest Helm version

      - name: Package Helm Chart
        run: |
          mkdir -p .deploy
          helm package charts/ --destination .deploy

      - name: Checkout gh-pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update Helm Chart Index
        run: |
          cd gh-pages
          mv ../.deploy/*.tgz .
          helm repo index . --merge index.yaml || helm repo index .
          cd ..

      - name: Commit and Push Changes
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Helm chart" || echo "No changes to commit"
          git push
