name: Deploy Helm Chart to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        deployments: write
        pages: write
        packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.3  # Adjust to the latest Helm version

      - name: Install yq (YAML Processor)
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Checkout gh-pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Extract Version from Chart.yaml
        id: get_version
        run: |
          for chart in charts/*; do
            CHART_NAME=$(basename "$chart")
            CHART_PATH="$chart/Chart.yaml"
            
            CHART_VERSION=$(yq '.version' "$CHART_PATH")
            
            echo "Processing: $CHART_NAME - Version: $CHART_VERSION"
            
            echo "CHART_NAME_$CHART_NAME=$CHART_NAME" >> $GITHUB_ENV
            echo "CHART_VERSION_$CHART_NAME=$CHART_VERSION" >> $GITHUB_ENV
          done

      - name: Package Helm Chart
        run: |
          mkdir -p .deploy
          for chart in charts/*; do
            helm package "$chart" --destination .deploy
          done


      - name: Update Helm Chart Index
        run: |
          cd gh-pages
          mv ../.deploy/*.tgz .
          helm repo index . --merge index.yaml || helm repo index .
          cd ..

      - name: Commit and Push Changes
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Release Helm chart v$CHART_VERSION" || echo "No changes to commit"
          git push
