name: Release Helm Charts

on:
  push:
    tags:
      - "v*"  # Runs only when a new tag (e.g., v1.2.3) is pushed

jobs:
  release-charts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart_dir: ./charts/*  # Iterate over subdirectories in 'charts'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          helm-version: "latest"

      - name: Package Chart
        run: helm package ${{ matrix.chart_dir }}

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./*.tgz # Upload all .tgz files in the root
          asset_name: ${{ steps.package-chart.outputs.chart_file }}

      - name: Generate index.yaml
        run: helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Commit index.yaml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Helm Chart Index"
          file_pattern: index.yaml
          branch: gh-pages

      - name: Deploy to GitHub Pages (if needed)
        uses: actions/deploy-pages@v2
        if: github.ref == 'refs/heads/main'
        with:
          path: .
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          source: '.'
          path: '/'