name: Deploy Helm Chart

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.11.0'

    - name: Install Helm Push Plugin
      run: |
        helm plugin install https://github.com/chartmuseum/helm-push.git

    - name: Package Helm Chart
      run: |
        helm package chart

    - name: Push Helm Chart to HTTP Repository
      env:
        HELM_REPO_URL: "https://charts.example.com"  # Replace with your actual chart repo URL
        HELM_REPO_USERNAME: ${{ secrets.HELM_REPO_USERNAME }}
        HELM_REPO_PASSWORD: ${{ secrets.HELM_REPO_PASSWORD }}
      run: |
        helm repo add myrepo $HELM_REPO_URL --username $HELM_REPO_USERNAME --password $HELM_REPO_PASSWORD
        helm push $(ls *.tgz) myrepo
